kind: pipeline
name: test

trigger:
  event: [push]

steps:
  - name: frontend
    image: node:10.17.0-alpine3.10
    commands:
      - cd frontend
      - yarn install --pure-lockfile
      - yarn lint
    depends_on: [clone]

  - name: backend
    image: node:10.17.0-alpine3.10
    commands:
      - cd backend
      - yarn install --pure-lockfile
      - yarn lint
      - yarn test
    depends_on: [clone]
---
kind: pipeline
name: build

trigger:
  event: [push]
  branch: ["master"]

steps:
  - name: builder
    image: plugins/docker
    settings:
      target: builder
      username: { from_secret: quay_username }
      password: { from_secret: quay_password }
      registry: quay.io
      repo: quay.io/zebbra/timetracker
      tags: builder
      cache_from:
        - quay.io/zebbra/timetracker:builder
      custom_labels: [quay.expires-after=30d]
      mtu: 1316

  - name: release
    image: plugins/docker
    settings:
      username: { from_secret: quay_username }
      password: { from_secret: quay_password }
      registry: quay.io
      repo: quay.io/zebbra/timetracker
      tags: "latest,git-${DRONE_COMMIT_SHA:0:7}"
      cache_from:
        - quay.io/zebbra/timetracker:builder
        - quay.io/zebbra/timetracker:latest
      custom_labels: [quay.expires-after=30d]
      mtu: 1316
---
kind: pipeline
name: deploy

depends_on:
  - test
  - build

trigger:
  event: [push]
  branch: ["master"]

steps:
  - name: helm
    image: pelotech/drone-helm3
    environment:
      API_SERVER: https://kubernetes.default
      KUBERNETES_TOKEN: { from_secret: kubernetes_token }
    settings:
      mode: upgrade
      chart: ./deploy/helm
      release: timetracker
      namespace: medi-timetracker
      values: image.tag=git-${DRONE_COMMIT_SHA:0:7}
      # values_files:
      #   - ./deploy/production.yaml
      reuse_values: false
      skip_tls_verify: true
